SELECT * FROM EMPLOYEE;
SELECT EMP_NO, EMP_NAME, DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE JOB_CODE = 'J1';
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY FROM EMPLOYEE WHERE SALARY >= 3000000 AND JOB_CODE = 'J2';

